// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

import (
	"time"
)

// Error エラーメッセージモデル
type Error struct {
	Message string `json:"message"`
}

// LastReleased 最終リリース設定モデル
type LastReleased struct {
	ImageUri   string    `json:"image_uri"`
	ReleasedAt time.Time `json:"released_at"`
}

// NextRelease リリース待ち設定モデル
type NextRelease struct {
	ImageUri  string    `json:"image_uri"`
	ReleaseAt time.Time `json:"release_at"`
}

// TagSetting タグ形式リリース設定モデル
type TagSetting struct {
	EnvironmentName string    `json:"environment_name"`
	Tags            *[]string `json:"tags,omitempty"`
}

// UriSetting URI形式リリース設定モデル
type UriSetting struct {
	EnvironmentName string `json:"environment_name"`

	// LastReleased 最終リリース設定モデル
	LastReleased *LastReleased `json:"last_released,omitempty"`

	// NextRelease リリース待ち設定モデル
	NextRelease *NextRelease `json:"next_release,omitempty"`
	ServiceName string       `json:"service_name"`
}

// ErrorResponse エラーメッセージモデル
type ErrorResponse = Error

// TagSettingResponse defines model for tagSettingResponse.
type TagSettingResponse = []TagSetting

// UriSettingResponse defines model for uriSettingResponse.
type UriSettingResponse = []UriSetting
