// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

import (
	"time"
)

// Error エラーメッセージモデル
type Error struct {
	Message string `json:"message"`
}

// LastReleased 最終リリース設定モデル
type LastReleased struct {
	ImageUri   string    `json:"image_uri"`
	ReleasedAt time.Time `json:"released_at"`
}

// NextRelease リリース待ち設定モデル
type NextRelease struct {
	ImageUri  string    `json:"image_uri"`
	ReleaseAt time.Time `json:"release_at"`
}

// Tag タグ形式リリース設定モデル
type Tag struct {
	RepositoryName string    `json:"repository_name"`
	SettingTitle   string    `json:"setting_title"`
	SettingUrl     string    `json:"setting_url"`
	Tags           *[]string `json:"tags,omitempty"`
}

// Uri URI形式リリース設定モデル
type Uri struct {
	// LastReleased 最終リリース設定モデル
	LastReleased *LastReleased `json:"last_released,omitempty"`

	// NextRelease リリース待ち設定モデル
	NextRelease  *NextRelease `json:"next_release,omitempty"`
	ServiceName  string       `json:"service_name"`
	SettingTitle string       `json:"setting_title"`
	SettingUrl   string       `json:"setting_url"`
}

// ErrorResponse エラーメッセージモデル
type ErrorResponse = Error

// TagSettingResponse defines model for tagSettingResponse.
type TagSettingResponse = []Tag
